name: publish-image

on:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@4935fe307bbde00c895e19be00476904f61bbfa1 # 2.0.4
    with:
      image-name: semaphore
    secrets:
      registry-password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
